### PR TITLE
2 day article template

### PR DESCRIPTION
**Pull request by cmgorton**
Adding in edits for the templates and cleaning up grammar.

### CODE REVIEW

**Review by madebygps — APPROVED** [review]
Looks great 👍

**Review by madebygps — APPROVED** [review]
Looks great

**Review by rishabkumar7 — APPROVED** [review]
Looks good 👍

**Review by madebygps — APPROVED** [review]

**Review by madebygps — APPROVED** [review]

**Review by what-name — APPROVED** [review]
💪🏻

**Review by what-name — APPROVED** [review]

**Pull request merged**
